# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import peeldb.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0014_post_slugs'),
        ('peeldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('attached_file', models.FileField(blank=True, max_length=1000, null=True, upload_to=peeldb.models.img_url)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_blog_it.Post')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
