# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-11 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0005_auto_20170211_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('blog_view', 'can view blog posts and categories'),
                                    ('blog_edit', 'can edit blog category and post'),
                                    ('support_view', 'can view tickets'), ('support_edit', 'can edit tickets'),
                                    ('activity_view', 'can view recruiters, applicants, data, posts'),
                                    ('activity_edit', 'can edit data'), ('jobposts_edit', 'can manage jobposts'),
                                    ('jobposts_invoice_access', 'can manage invoice'),
                                    ('jobposts_resume_profiles', 'can manage resume profiles'))},
        ),
    ]
