# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0006_auto_20170211_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="major_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="major_skill",
                to="peeldb.Skill",
            ),
        ),
    ]
