# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0007_auto_20170213_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='campaign_icon',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
