# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0013_auto_20170321_1431"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobpost",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full Time"),
                    ("internship", "Internship"),
                    ("walk-in", "Walk-in"),
                    ("governament", "Government"),
                    ("Fresher", "Fresher"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="searchresult",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full-time", "Full Time"),
                    ("internship", "Internship"),
                    ("walk-in", "Walk-in"),
                    ("governament", "Government"),
                    ("Fresher", "Fresher"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
