# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0016_jobpost_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlefirend',
            name='email',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
