# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0017_auto_20170704_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternate_mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
