# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0019_company_created_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True),
        ),
    ]