# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0023_qualification_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='ip_address',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='user_agent',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
