# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0026_auto_20170802_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(max_length=5000),
        ),
    ]
