# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 15:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0026_auto_20170810_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='skill',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
