# Generated by Django 3.1.1 on 2020-09-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0048_auto_20200805_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_admin',
            field=models.BooleanField(default=False),
        ),
    ]
