# Generated by Django 3.2.11 on 2022-04-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0052_rename_job_id_usermessage_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="meta",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="meta",
            field=models.JSONField(null=True),
        ),
    ]
