# Generated by Django 5.2.2 on 2025-06-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0057_alter_agencycompany_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_looking_for_job",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_open_to_offers",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_description",
            field=models.CharField(default="", max_length=5000),
        ),
    ]
