# Generated by Django 5.2.2 on 2025-06-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0058_user_is_looking_for_job_user_is_open_to_offers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employmenthistory",
            name="salary",
        ),
    ]
