# Generated by Django 5.2.2 on 2025-10-24 09:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0066_remove_teaminvitation_unique_company_email_invitation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='fb_groups',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='fb_views',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='ln_views',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='other_views',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='post_on_fb',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='post_on_ln',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='post_on_tw',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='posted_on',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='previous_status',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='published_message',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='tw_views',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='application_method',
            field=models.CharField(choices=[('portal', 'Apply on Portal'), ('external', 'External URL'), ('email', 'Email')], default='portal', help_text='How candidates should apply for this job', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='application_url',
            field=models.URLField(blank=True, help_text="External URL for job applications (if application_method is 'external')", null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='List of benefits: PF, ESI, Health Insurance, Annual Bonus, etc.', null=True, size=None),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='hiring_priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal', help_text='Urgency level for filling this position', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='hiring_timeline',
            field=models.CharField(blank=True, choices=[('1-3days', '1-3 Days'), ('1-2weeks', '1-2 Weeks'), ('1month', '1 Month'), ('1-3months', '1-3 Months')], help_text='Target time to fill this position', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='language_requirements',
            field=models.JSONField(blank=True, help_text='Required languages with proficiency levels', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='preferred_certifications',
            field=models.TextField(blank=True, help_text='Preferred/nice-to-have certifications'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='relocation_required',
            field=models.BooleanField(default=False, help_text='Is candidate willing to relocate required?'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_certifications',
            field=models.TextField(blank=True, help_text='Required certifications (comma-separated or free text)'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seniority_level',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager')], help_text='Role level (Intern, Junior, Mid, Senior, Lead, Manager)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='show_salary',
            field=models.BooleanField(default=True, help_text='Show salary range to job seekers'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='travel_percentage',
            field=models.CharField(blank=True, help_text="Expected travel percentage (e.g., '0-10%', '10-25%', '25-50%')", max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_links',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('permanent', 'Permanent'), ('contract', 'Contract'), ('internship', 'Internship'), ('part-time', 'Part Time'), ('freelance', 'Freelance'), ('walk-in', 'Walk-in'), ('government', 'Government'), ('fresher', 'Fresher')], max_length=50),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full-time', 'Full Time'), ('permanent', 'Permanent'), ('contract', 'Contract'), ('internship', 'Internship'), ('part-time', 'Part Time'), ('freelance', 'Freelance'), ('walk-in', 'Walk-in'), ('government', 'Government'), ('fresher', 'Fresher')], max_length=20, null=True),
        ),
    ]
