# Generated by Django 5.2.2 on 2025-10-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0067_remove_screening_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='functional_area',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='functional_area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='functional_area',
        ),
    ]
