# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0002_blogattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_admin',
            field=models.BooleanField(default=False),
        ),
    ]
