# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0020_auto_20170717_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
