# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0031_auto_20170911_1817"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="skill_type",
            field=models.CharField(
                choices=[
                    ("technical", "Technical"),
                    ("non-technical", "Non-Technical"),
                    ("other", "Other"),
                ],
                default="technical",
                max_length=20,
            ),
        ),
    ]
