# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0037_remove_user_is_register_through_mail"),
        ("peeldb", "0037_auto_20171030_1100"),
    ]

    operations = []
