# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0038_merge_20171030_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobalert",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="subscribe_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="subscribe_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
