# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0039_auto_20171031_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobalert",
            name="unsubscribe_reason",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="unsubscribe_reason",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="unsubscribe_reason",
            field=models.TextField(default=""),
        ),
    ]
