# Generated by Django 3.0.8 on 2020-07-31 12:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0046_auto_20191209_1910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name="searchresult",
            name="search_text",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name="skill",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
