# Generated by Django 3.1 on 2020-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0047_auto_20200731_1221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="meta",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="searchresult",
            name="search_text",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="skill",
            name="meta",
            field=models.JSONField(),
        ),
    ]
