# Generated by Django 4.2.19 on 2025-02-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0053_auto_20220412_0906"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoogleFirend",
        ),
    ]
