# Generated by Django 4.2.22 on 2025-06-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0054_delete_googlefirend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facebookgroup",
            name="user",
        ),
        migrations.RemoveField(
            model_name="facebookpage",
            name="user",
        ),
        migrations.RemoveField(
            model_name="facebookpost",
            name="job_post",
        ),
        migrations.RemoveField(
            model_name="linkedin",
            name="user",
        ),
        migrations.RemoveField(
            model_name="linkedinfriend",
            name="user",
        ),
        migrations.RemoveField(
            model_name="linkedingroup",
            name="user",
        ),
        migrations.RemoveField(
            model_name="linkedinpost",
            name="job_post",
        ),
        migrations.RemoveField(
            model_name="stackoverflow",
            name="user",
        ),
        migrations.RemoveField(
            model_name="twitter",
            name="user",
        ),
        migrations.RemoveField(
            model_name="twitterfollower",
            name="user",
        ),
        migrations.RemoveField(
            model_name="twitterfriend",
            name="user",
        ),
        migrations.RemoveField(
            model_name="twitterpost",
            name="job_post",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="minified_url",
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agencyresume",
            name="status",
            field=models.CharField(
                choices=[
                    ("Page", "Page"),
                    ("Profile", "Profile"),
                    ("Group", "Group"),
                    ("Profile", "Profile"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appliedjobs",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Shortlisted", "Shortlisted"),
                    ("Hired", "Hired"),
                    ("Rejected", "Rejected"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mailtemplate",
            name="applicant_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Shortlisted", "Shortlisted"),
                    ("Hired", "Hired"),
                    ("Rejected", "Rejected"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="FacebookFriend",
        ),
        migrations.DeleteModel(
            name="FacebookGroup",
        ),
        migrations.DeleteModel(
            name="FacebookPage",
        ),
        migrations.DeleteModel(
            name="FacebookPost",
        ),
        migrations.DeleteModel(
            name="Linkedin",
        ),
        migrations.DeleteModel(
            name="LinkedinFriend",
        ),
        migrations.DeleteModel(
            name="LinkedinGroup",
        ),
        migrations.DeleteModel(
            name="LinkedinPost",
        ),
        migrations.DeleteModel(
            name="StackOverFlow",
        ),
        migrations.DeleteModel(
            name="Twitter",
        ),
        migrations.DeleteModel(
            name="TwitterFollower",
        ),
        migrations.DeleteModel(
            name="TwitterFriend",
        ),
        migrations.DeleteModel(
            name="TwitterPost",
        ),
    ]
