# Generated by Django 5.2.2 on 2025-06-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0055_remove_facebookgroup_user_remove_facebookpage_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="parent_city",
        ),
    ]
