# Generated by Django 5.2.2 on 2025-06-16 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0059_remove_employmenthistory_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("organization", models.CharField(max_length=500)),
                (
                    "credential_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "credential_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("does_not_expire", models.BooleanField(default=False)),
                (
                    "description",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_date", "-created_at"],
            },
        ),
    ]
