# Generated by Django 5.2.2 on 2025-10-29 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0068_remove_functional_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinstitue',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='peeldb.city'),
        ),
    ]
