# Generated by Django 5.2.2 on 2025-10-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0069_make_educationinstitue_city_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='last_date',
        ),
    ]
