# Generated by Django 5.2.2 on 2025-12-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0070_remove_last_date_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='question',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='question',
            name='solutions',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='given_by',
        ),
        migrations.DeleteModel(
            name='AssessmentData',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
