# Generated by Django 5.2.9 on 2026-02-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0071_remove_assessment_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='user',
        ),
        migrations.DeleteModel(
            name='Facebook',
        ),
        migrations.DeleteModel(
            name='GitHub',
        ),
    ]
